# Generated by Django 4.2.16 on 2024-12-01 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bettergtm_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='fiirst_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Team',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Role',
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bettergtm_backend.customer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bettergtm_backend.role'),
        ),
    ]
