# Generated by Django 4.2.16 on 2024-12-13 03:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bettergtm_backend', '0005_alter_customer_id_alter_goals_id_alter_outputs_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goals',
            new_name='Goal',
        ),
        migrations.RenameModel(
            old_name='Outputs',
            new_name='Output',
        ),
    ]
